apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schema-registry-dev1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michaeljkavanagh-irl/cdcpoc-helm.git
    targetRevision: main
    path: apps/schema-registry
    helm:
      valueFiles:
        - values-dev1.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
