nameOverride: schema-registry
namespace: data-platform
replicaCount: 1
image:
  repository: confluentinc/cp-schema-registry
  tag: 7.8.0
  pullPolicy: IfNotPresent
service:
  port: 8081
env:
  SCHEMA_REGISTRY_HOST_NAME: schema-registry
  SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
